modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="seamless_loading_screen"
version="${file.jarVersion}"
displayName="Seamless Loading Screen"
authors="Minenash, Forge Port: DaDerpDuck"
description='''
Forge port of Seamless Loading Screen
Takes a screenshot of the game when you leave a world or server, and displays it when you rejoin it
'''

[[dependencies.seamless_loading_screen]]
    modId="forge"
    mandatory=true
    versionRange="36,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.seamless_loading_screen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="CLIENT"