modLoader="javafml"
loaderVersion="${loader_range}"
license="MIT"

[[mods]]
modId="seamless_loading_screen"
version="${file.jarVersion}"
displayName="Seamless Loading Screen"
authors="Minenash, Forge Port: DaDerpDuck"
description='''
Forge port of Seamless Loading Screen
Takes a screenshot of the game when you leave a world or server, and displays it when you rejoin it
'''

[[dependencies.seamless_loading_screen]]
    modId="forge"
    mandatory=true
    versionRange="${forge_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.seamless_loading_screen]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_range}"
    ordering="NONE"
    side="CLIENT"